# Importing important libraries

In [4]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

# Reading dataset

In [5]:
Train = pd.read_csv("../input/fake-news/train.csv")


In [6]:
# here we are printing first five lines of our train dataset
Train.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

# Data Pre-Processing

In [7]:
# here we are Getting the Independent Features
X=Train.drop('label',axis=1)

In [8]:
# printing head of our independent features
X.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [9]:
# here we are printing shape of our dataset
Train.shape


(20800, 5)

In [10]:
# here we are checking if there is null value or not
Train.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [11]:
# here we are droping NaN values from our dataset
Train=Train.dropna()

In [12]:
# here we are checking again if there is any NaN value or not
Train.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [13]:
Train.head(10)

id                                              title  \
0    0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1    1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2    2                  Why the Truth Might Get You Fired   
3    3  15 Civilians Killed In Single US Airstrike Hav...   
4    4  Iranian woman jailed for fictional unpublished...   
5    5  Jackie Mason: Hollywood Would Love Trump if He...   
7    7  Benoît Hamon Wins French Socialist Party’s Pre...   
9    9  A Back-Channel Plan for Ukraine and Russia, Co...   
10  10  Obama’s Organizing for Action Partners with So...   
11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                          author  \
0                  Darrell Lucus   
1                Daniel J. Flynn   
2             Consortiumnews.com   
3                Jessica Purkiss   
4                 Howard Portnoy   
5                Daniel Nussbaum   
7                Alissa J. Rubin   
9   Megan Twohey and Scott Shane   
10                   Aaron Klein   
11               Chris Tomlinson   

                                                 text  label  
0   House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1   Ever get the feeling your life circles the rou...      0  
2   Why the Truth Might Get You Fired October 29, ...      1  
3   Videos 15 Civilians Killed In Single US Airstr...      1  
4   Print \nAn Iranian woman has been sentenced to...      1  
5   In these trying times, Jackie Mason is the Voi...      0  
7   PARIS  —   France chose an idealistic, traditi...      0  
9   A week before Michael T. Flynn resigned as nat...      0  
10  Organizing for Action, the activist group that...      0  
11  The BBC produced spoof on the “Real Housewives...      0

as above we are observing that after removing NaN values index number 6 and number 8 is missing because they are NaN value so they are get removed so for managing index we have to do index reseting

In [14]:
# here we are copying our dataset .
df=Train.copy()

In [15]:
# here we are reseting our index
df.reset_index(inplace=True)

In [21]:
# here we are printing our first 10 line of dataset for checking indexing
df.head(10)

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   
5      5   5  Jackie Mason: Hollywood Would Love Trump if He...   
6      7   7  Benoît Hamon Wins French Socialist Party’s Pre...   
7      9   9  A Back-Channel Plan for Ukraine and Russia, Co...   
8     10  10  Obama’s Organizing for Action Partners with So...   
9     11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                         author  \
0                 Darrell Lucus   
1               Daniel J. Flynn   
2            Consortiumnews.com   
3               Jessica Purkiss   
4                Howard Portnoy   
5               Daniel Nussbaum   
6               Alissa J. Rubin   
7  Megan Twohey and Scott Shane   
8                   Aaron Klein   
9               Chris Tomlinson   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1  
5  In these trying times, Jackie Mason is the Voi...      0  
6  PARIS  —   France chose an idealistic, traditi...      0  
7  A week before Michael T. Flynn resigned as nat...      0  
8  Organizing for Action, the activist group that...      0  
9  The BBC produced spoof on the “Real Housewives...      0

In [22]:
x=df['title']
# here we are making independent features
y=df['label']
y.shape

(18285,)

In [23]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [24]:
ps = PorterStemmer()
corpus = []
for i in range(0, len(Train)):
    review = re.sub('[^a-zA-Z]', ' ', df['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [26]:
corpus[30]

'russia move ban jehovah wit extremist new york time'

In [29]:
# here we are setting vocabulary size
voc_size=5000

In [30]:
# performing one hot representation
from tensorflow.keras.preprocessing.text import one_hot
one_hot_rep=[one_hot(words,voc_size)for words in corpus] 

In [31]:
# here we are printing length of first line
len(one_hot_rep[0])

10

In [32]:
# here we are printing length of 70 line
len(one_hot_rep[70])

9

In [33]:
#  importing library for doind padding
from tensorflow.keras.preprocessing.sequence import pad_sequences
# specifying a sentence length so that every sentence in the corpus will be of same length

sentence_length=25

#using padding for creating equal length sentences


embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sentence_length)
print(embedded_docs)

[[   0    0    0 ... 2956 2146  274]
 [   0    0    0 ... 4049 4696  399]
 [   0    0    0 ... 1007 2914 2456]
 ...
 [   0    0    0 ... 3941 1441 4967]
 [   0    0    0 ... 2659  460 3460]
 [   0    0    0 ... 1287 3342 4183]]


# Building Models

In [34]:
# imporitng important libraries for building model
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

In [42]:
#Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sentence_length))
model.add(Dropout(0.3))
model.add(LSTM(200))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])


In [43]:
z =np.array(embedded_docs)
y =np.array(y)

In [44]:
#  printing shape 
z.shape,y.shape

((18285, 25), (18285,))

# Spiliting and Training

In [45]:
# splitting the data for training and testing the model

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(z, y, test_size=0.10, random_state=42)


In [46]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=20,batch_size=64)

Epoch 1/20
258/258 [==============================] - 9s 36ms/step - loss: 0.2954 - accuracy: 0.8633 - val_loss: 0.2028 - val_accuracy: 0.9049
Epoch 2/20
258/258 [==============================] - 9s 35ms/step - loss: 0.1477 - accuracy: 0.9421 - val_loss: 0.2142 - val_accuracy: 0.9142
Epoch 3/20
258/258 [==============================] - 9s 34ms/step - loss: 0.1142 - accuracy: 0.9562 - val_loss: 0.2202 - val_accuracy: 0.9071
Epoch 4/20
258/258 [==============================] - 9s 34ms/step - loss: 0.0847 - accuracy: 0.9706 - val_loss: 0.2356 - val_accuracy: 0.9169
Epoch 5/20
258/258 [==============================] - 9s 35ms/step - loss: 0.0647 - accuracy: 0.9765 - val_loss: 0.2697 - val_accuracy: 0.9092
Epoch 6/20
258/258 [==============================] - 9s 34ms/step - loss: 0.0474 - accuracy: 0.9830 - val_loss: 0.3140 - val_accuracy: 0.9125
Epoch 7/20
258/258 [==============================] - 9s 34ms/step - loss: 0.0386 - accuracy: 0.9855 - val_loss: 0.3521 - val_accuracy: 0.9076

In [51]:
#  loading our test dataset for prediction

Test=pd.read_csv('../input/fake-news/test.csv') 
Test_id=Test["id"]

In [52]:
Test_id

0       20800
1       20801
2       20802
3       20803
4       20804
        ...  
5195    25995
5196    25996
5197    25997
5198    25998
5199    25999
Name: id, Length: 5200, dtype: int64

In [56]:
Test_id.shape

(5200,)

In [54]:
# printing first 5 line of our dataset
Test.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [58]:
# removing these columns as they are not so important
Test=Test.drop(['text','id','author'],axis=1)

In [59]:
# printing first 5 line of our dataset
Test.head()

title
0  Specter of Trump Loosens Tongues, if Not Purse...
1  Russian warships ready to strike terrorists ne...
2  #NoDAPL: Native American Leaders Vow to Stay A...
3  Tim Tebow Will Attempt Another Comeback, This ...
4                    Keiser Report: Meme Wars (E995)

In [60]:
# checking if null values in the test dataset or not

Test.isnull().sum()

title    122
dtype: int64

In [64]:
Test.fillna('fake fake fake',inplace=True)
# here we are filling NaN value with "fake,fake,fake".we cannot drop the NaN value because
# as the solution file that we have to submitted in kaggle expects 
# it to have 5200 rows so we can't drop rows in the test dataset

In [61]:
# here we are printing shape
Test.shape

(5200, 1)

In [65]:
# creating corpus for the test dataset exactly the same as we created for the 
# training dataset
ps = PorterStemmer()
corpus_test = []
for i in range(0, len(Test)):
    review = re.sub('[^a-zA-Z]', ' ',Test['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus_test.append(review)

In [63]:
corpus[30]

'russia move ban jehovah wit extremist new york time'

In [67]:
# creating one hot representation for the test corpus

one_hot_rep_Test=[one_hot(words,voc_size)for words in corpus_test] 

In [68]:
# padding for the test dataset
sentence_length=25

embedded_docs_test=pad_sequences(one_hot_rep_Test,padding='pre',maxlen=sentence_length)
print(embedded_docs_test)

[[   0    0    0 ... 3941 1441 4967]
 [   0    0    0 ... 1575 1751 4104]
 [   0    0    0 ... 3647 2108 4758]
 ...
 [   0    0    0 ... 3941 1441 4967]
 [   0    0    0 ... 2393  644 1162]
 [   0    0    0 ... 3941 1441 4967]]


In [69]:
x_test=np.array(embedded_docs_test)

In [78]:
#making predictions for the test dataset

fakedetect=model.predict_classes(x_test)

In [79]:
fakedetect

array([[0],
       [1],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [80]:
fakedetect.shape

(5200, 1)

In [81]:
Test.shape

(5200, 1)

# Creating  a fake news dataframe from the test dataset

In [82]:
val=[]
for i in check:
    val.append(i[0])

In [83]:
FakeN = pd.DataFrame({'id':Test_id, 'label':val})
FakeN.shape

(5200, 2)

In [76]:
FakeN.head()

id  label
0  20800      0
1  20801      1
2  20802      0
3  20803      0
4  20804      1